version: '3.4'

services:
  #nginx:
  #  volumes:
  #    - ./nginx/conf.d.dev:/etc/nginx/conf.d

  bot.datastore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/certs/localhost.pfx
    volumes:
      - ./keys/datastore:/root/.aspnet/DataProtection-Keys
      - ./ssl:/root/.aspnet/certs:ro

  bot.webservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_BOT_DATA_STORE_ENDPOINT=https://datastore
      - ASPNETCORE_BOT_API_KEY=330040075:AAHF7mtl1CEQ39fPXKteifC0yKyADvhMh3A
      - ASPNETCORE_ALLOWED_USERS=Py6jlb||ahfksdfsd||sdfjkhsdkfjh

  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80