version: '3.4'

networks:
  app:
    driver: "bridge"

services:
  bot.datastore:
    image: ${DOCKER_REGISTRY-}botdatastore
    build:
      context: ..
      dockerfile: src/Bot.DataStore/Dockerfile
    volumes:
      - ../src/Bot.DataStore/db:/app/db
    networks:
      app:
        aliases:
          - "datastore"    

  bot.webservice:
    image: ${DOCKER_REGISTRY-}botwebservice
    build:
      context: ..
      dockerfile: src/Bot.WebService/Dockerfile
    environment:
      - ASPNETCORE_USE_REVERSE_PROXY=true
      - ASPNETCORE_BOT_API_KEY=330040075:AAHF7mtl1CEQ39fPXKteifC0yKyADvhMh3A
      - ASPNETCORE_ALLOWED_USERS=Py6jlb||ahfksdfsd||sdfjkhsdkfjh
      - ASPNETCORE_BOT_DATA_STORE_ENDPOINT=https://datastore123
      - ASPNETCORE_SUBDIR=/web
      - ASPNETCORE_ISSUER_URI=https://localhost/web
    networks:
      app:

