version: '3.4'

services:
  bot.datastore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
#  bot.telegramworker:
#    environment:
#      - DOTNET_ENVIRONMENT=Development
#      - DOTNET_BOT_DATA_STORE_ENDPOINT=https://datastore

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000"
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
